//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP2.HRMS.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttnID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime LogTime { get; set; }
    
        public virtual EmployeeInfo EmployeeInfo { get; set; }
    }
}
