//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOP2.HRMS.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeInfo()
        {
            this.Attendances = new HashSet<Attendance>();
            this.EmployeeSalaries = new HashSet<EmployeeSalary>();
            this.LeaveForms = new HashSet<LeaveForm>();
            this.Payslips = new HashSet<Payslip>();
        }
    
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public string Email { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime HireDate { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string BloodGroup { get; set; }
        public int DeptID { get; set; }
        public int DesigID { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string Nationality { get; set; }
        public string NID { get; set; }
        public string Religion { get; set; }
        public string Contact { get; set; }
        public string Status { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalary> EmployeeSalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveForm> LeaveForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payslip> Payslips { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
