
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OOP2.HRMS.DATA
{

using System;
    using System.Collections.Generic;
    
public partial class LeaveForm
{

    public int EmpID { get; set; }

    public int LeaveID { get; set; }

    public string Type { get; set; }

    public string Period { get; set; }

    public Nullable<System.DateTime> FromDate { get; set; }

    public Nullable<System.DateTime> ToDate { get; set; }

    public string NoOfDays { get; set; }

    public int Status { get; set; }



    public virtual EmployeeInfo EmployeeInfo { get; set; }

}

}
