
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OOP2.HRMS.DATA
{

using System;
    using System.Collections.Generic;
    
public partial class Payslip
{

    public int ID { get; set; }

    public int EmpID { get; set; }

    public int PayrollID { get; set; }

    public int BasicSalary { get; set; }

    public int HouseAllowance { get; set; }

    public int Medical { get; set; }

    public int Conveyance { get; set; }

    public int Addition { get; set; }

    public int Deduction { get; set; }

    public string StatusID { get; set; }

    public System.DateTime Date { get; set; }



    public virtual EmployeeInfo EmployeeInfo { get; set; }

    public virtual Payroll Payroll { get; set; }

}

}
